import { PATTERNS } from "./scanner/patterns";
import type { ScanResult } from "./types";

const has = (scan: ScanResult, key: string) => key in scan.signals;
const vendors = (scan: ScanResult) => PATTERNS.filter((p) => p.vendor && has(scan, p.signal)).map((p) => p.vendor!.name);

const banner = (scan: ScanResult) =>
  `> DRAFT generated by ShipShape on ${scan.createdAt.slice(0, 10)} from what the code at ${scan.target} does.\n` +
  `> This is a starting point, not legal advice. Review it, edit it and have a lawyer check it before you publish.\n`;

/** A privacy policy draft that only describes what the scan actually found. */
export function privacyPolicy(scan: ScanResult, company = "[Company name]", contact = "[privacy@yourcompany.com]") {
  const v = vendors(scan);
  const data: string[] = [];
  if (has(scan, "feature:signup")) data.push("Account information you give us, such as your name and email address.");
  if (has(scan, "feature:image-upload")) data.push("Photos and images you choose to upload.");
  if (has(scan, "payments:card") || has(scan, "payments:iap")) data.push("Purchase records. Card details are handled by our payment provider, not stored by us.");
  if (has(scan, "ai:sdk")) data.push("Messages you send to our AI features, which are processed by our AI provider to generate replies.");
  if (v.length) data.push("Device and usage information, such as pages or screens viewed, collected through the analytics and advertising services listed below.");

  return `${banner(scan)}
# Privacy Policy

Last updated: ${scan.createdAt.slice(0, 10)}

${company} ("we") explains here what information our product collects, why, and the choices you have.

## Information we collect

${data.length ? data.map((d) => `- ${d}`).join("\n") : "- We do not knowingly collect personal information."}

## Services we share information with

${v.length ? v.map((n) => `- ${n}`).join("\n") : "- We do not share personal information with analytics or advertising services."}

## Your choices

${has(scan, "feature:account-deletion") ? "- You can delete your account at any time from within the app. Deleting your account removes your personal information except where we must keep it by law.\n" : has(scan, "feature:signup") ? "- [ShipShape found sign up but no account deletion. Add in app deletion, then describe it here.]\n" : ""}- California residents can ask what we collect, ask us to delete it, and opt out of the sale or sharing of personal information. We honor Global Privacy Control signals.
- To make a request, contact ${contact}.

## Children

Our product is not directed to children under 13, and we do not knowingly collect their personal information.

## Contact

${company}, ${contact}
`;
}

export function termsOfService(scan: ScanResult, company = "[Company name]") {
  return `${banner(scan)}
# Terms of Service

Last updated: ${scan.createdAt.slice(0, 10)}

By using ${company}'s product you agree to these terms.

## Your account
${has(scan, "feature:signup") ? `You are responsible for your account and for keeping your login secure.${has(scan, "feature:account-deletion") ? " You can delete your account at any time." : ""}` : "No account is needed to use the product."}

${has(scan, "feature:image-upload") ? "## Your content\nYou keep ownership of what you upload and give us permission to store and show it to run the product. Do not upload content you don't have the right to share. To report content, including intimate images shared without consent, use the report option or contact us; we remove valid reports within 48 hours.\n" : ""}
${has(scan, "payments:card") || has(scan, "payments:iap") ? "## Payments\nPrices are shown before you buy. Subscriptions renew until you cancel.\n" : ""}
${has(scan, "ai:sdk") ? "## AI features\nReplies are generated by AI, may be wrong, and are not professional advice. You are talking to an AI, not a person.\n" : ""}
## Limitation of liability
To the extent the law allows, ${company}'s total liability is limited to the amount you paid us in the 12 months before the claim.

## Changes
We will post changes to these terms here and update the date above.
`;
}

/** Suggested answers for the App Store privacy label and Google Play Data safety form. */
export function storeAnswers(scan: ScanResult) {
  const rows: [string, string, string][] = [];
  if (has(scan, "feature:signup")) rows.push(["Contact info (email, name)", "App functionality", "Linked to the user"]);
  if (has(scan, "feature:image-upload")) rows.push(["User content (photos)", "App functionality", "Linked to the user"]);
  if (has(scan, "payments:card") || has(scan, "payments:iap")) rows.push(["Purchases", "App functionality", "Linked to the user"]);
  if (has(scan, "tracker:meta") || has(scan, "tracker:ads") || has(scan, "tracker:tiktok")) rows.push(["Identifiers and usage data", "Third party advertising; used for tracking", "Linked to the user"]);
  for (const name of ["google-analytics", "mixpanel", "amplitude", "segment", "posthog", "hotjar", "clarity"]) {
    if (has(scan, `tracker:${name}`)) {
      rows.push(["Usage data and diagnostics", "Analytics", "Check the SDK settings"]);
      break;
    }
  }
  return `${banner(scan)}
# Store privacy answers

| Data type | Purpose | Linked to user |
| --- | --- | --- |
${rows.length ? rows.map((r) => `| ${r.join(" | ")} |`).join("\n") : "| No data collected found | | |"}

Check each SDK's own privacy documentation; SDKs can collect more than your code calls directly.
`;
}
